//USER 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
// CHILDREN TYPES 
export const GET_CHILDREN = 'GET_CHILDREN';
export const ADD_CHILDREN = 'ADD_CHILDREN';
export const DELETE_CHILDREN = 'DELETE_CHILDREN';
export const UPDATE_CHILDREN = 'UPDATE_CHILDREN';
export const SET_CURRENT_CHILD = 'SET_CURRENT_CHILD';
export const CLEAR_CURRENT_CHILDREN = 'CLEAR_CURRENT_CHILDREN';
export const FILTER_CHILDREN = 'FILTER_CHILDREN';
export const CLEAR_CHILDREN_FILTER = 'CLEAR_CHILDREN_FILTER';
export const CHILDREN_ERROR = 'CHILDREN_ERROR'
//CHORES 
export const GET_CHORES='GET_CHORES'
export const DELETE_CHORES='DELETE_CHORES'
export const UPDATE_CHORES='UPDATE_CHORES'
export const ADD_CHORES='ADD_CHORES'
export const CHORES_ERROR='CHORES_ERROR'
export const SET_CURRENT_CHORE = 'SET_CURRENT_CHORE'
export const GET_CHILDREN_AND_CHORES = 'GET_CHILDREN_AND_CHORES'